name: dibry_app
version: 1.0.0+1
publish_to: none
description: Project Akhir UKK RPL Perpustakaan Digital
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: 5.4.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
#  Library
  flutter_rating_bar: ^4.0.1
  persistent_bottom_nav_bar_v2: ^5.2.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.0.4
  flutter_image_slideshow: ^0.1.6
  flutter_launcher_icons: ^0.13.1
  iconsax: ^0.0.8
  google_fonts: ^5.1.0
  get: 4.6.6

#  Library
  email_validator: ^2.1.16
  shimmer: ^3.0.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/dibry.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/logo/
    - assets/background/
    - assets/images/
    - assets/kategori/
    - assets/bottombar/

